name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set release env
        run: echo "release_version=${GITHUB_REF_NAME/v/}" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Get modules
        run: go mod vendor
      - name: Test
        run: make test
      - name: Build
        run: make release
      - name: Package
        run: |
          rsync ./bin/github-webhooks-exporter_darwin_amd64 README.md LICENSE github-webhooks-exporter_darwin_amd64 && tar czvf github-webhooks-exporter_darwin_amd64.tar.gz github-webhooks-exporter_darwin_amd64
          rsync ./bin/github-webhooks-exporter_amd64 README.md LICENSE github-webhooks-exporter_linux_amd64 && tar czvf github-webhooks-exporter_linux_amd64.tar.gz github-webhooks-exporter_linux_amd64
          rsync ./bin/github-webhooks-exporter_amd64 README.md LICENSE github-webhooks-exporter_windows_amd64 && tar czvf github-webhooks-exporter_windows_amd64.tar.gz github-webhooks-exporter_windows_amd64
      - name: Release
        uses: softprops/action-gh-release@8a65c813553f4d05769635eb1b70180d25b9b61b
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            github-webhooks-exporter_darwin_amd64.tar.gz
            github-webhooks-exporter_linux_amd64.tar.gz
            github-webhooks-exporter_windows_amd64.tar.gz
